module.exports = {
  key: "default",
  minSoldCount: 5,
  minCartUsers: 1,
  lowStockThreshold: 15,
  highStockThreshold: 20,
  rotateEveryMs: 10000,
  active: true,
  liveMinViewers: 20,
  liveMaxViewers: 400,
  liveUpdateEveryMs: 2000,
  liveModeRotateEveryMs: 7000,
  liveNormalStepMin: 5,
  liveNormalStepMax: 40,
  liveSurgeStepMin: 35,
  liveSurgeStepMax: 140,
  liveCooldownStepMin: 35,
  liveCooldownStepMax: 140,
  liveSpikeChancePercent: 18,
};
