const express = require("express");
const productsRoutes = require("./products.routes");
const categoriesRoutes = require("./categories.routes");
const navbarRoutes = require("./navbar.routes");
const homeBannersRoutes = require("./homeBanners.routes");
const footerRoutes = require("./footer.routes");
const cargoRoutes = require("./cargo.routes");
const videoBannersRoutes = require("./videoBanners.routes");
const collectionRoutes = require("./collection.routes");
const sellerRoutes = require("./seller.routes");
const sellersRoutes = require("./sellers.routes");
const defaultProductPolicyRoutes = require("./defaultProductPolicy.routes");
const uzWarehouseRoutes = require("./uzWarehouse.routes");
const loginRoutes = require("./login.routes");
const profileRoutes = require("./profile.routes");
const wishlistRoutes = require("./wishlist.routes");
const cartRoutes = require("./cart.routes");
const searchRoutes = require("./search.routes");
const viewedAtRoutes = require("./viewedAt.routes");
const recommendationRoutes = require("./recommendation.routes");
const flashSaleCountdownRoutes = require("./flashSaleCountdown.routes");
const flashSaleLiveStatsRoutes = require("./flashSaleLiveStats.routes");
const flashSaleRuleConfigRoutes = require("./flashSaleRuleConfig.routes");
const adminNavbarRoutes = require("./adminNavbar.routes");
const adminVideoBannersRoutes = require("./adminVideoBanners.routes");
const adminUploadRoutes = require("./adminUpload.routes");
const sellerSubscriptionRoutes = require("./sellerSubscription.routes");
const commentRoutes = require("./comment.routes");
const pendingReviewRoutes = require("./pendingReview.routes");

const router = express.Router();

router.use(productsRoutes);
router.use(categoriesRoutes);
router.use(navbarRoutes);
router.use(homeBannersRoutes);
router.use(footerRoutes);
router.use(cargoRoutes);
router.use(videoBannersRoutes);
router.use(collectionRoutes);
router.use(sellerRoutes);
router.use(sellersRoutes);
router.use(defaultProductPolicyRoutes);
router.use(uzWarehouseRoutes);
router.use(loginRoutes);
router.use(profileRoutes);
router.use(wishlistRoutes);
router.use(cartRoutes);
router.use(searchRoutes);
router.use(viewedAtRoutes);
router.use(recommendationRoutes);
router.use(flashSaleLiveStatsRoutes);
router.use(flashSaleCountdownRoutes);
router.use(flashSaleRuleConfigRoutes);
router.use(adminNavbarRoutes);
router.use(adminVideoBannersRoutes);
router.use(adminUploadRoutes);
router.use(sellerSubscriptionRoutes);
router.use(commentRoutes);
router.use(pendingReviewRoutes);

module.exports = router;
