const express = require("express");
const productsRoutes = require("./products.routes");
const categoriesRoutes = require("./categories.routes");
const navbarRoutes = require("./navbar.routes");
const homeBannersRoutes = require("./homeBanners.routes");
const footerRoutes = require("./footer.routes");
const cargoRoutes = require("./cargo.routes");
const videoBannersRoutes = require("./videoBanners.routes");
const collectionRoutes = require("./collection.routes");
const sellerRoutes = require("./seller.routes");
const sellersRoutes = require("./sellers.routes");
const topSellersRoutes = require("./topSellers.routes");
const defaultProductPolicyRoutes = require("./defaultProductPolicy.routes");
const uzWarehouseRoutes = require("./uzWarehouse.routes");
const uzbProductDeliveryInfoRoutes = require("./uzbProductDeliveryInfo.routes");
const loginRoutes = require("./login.routes");
const profileRoutes = require("./profile.routes");
const wishlistRoutes = require("./wishlist.routes");
const cartRoutes = require("./cart.routes");
const searchRoutes = require("./search.routes");
const viewedAtRoutes = require("./viewedAt.routes");
const recommendationRoutes = require("./recommendation.routes");
const flashSaleCountdownRoutes = require("./flashSaleCountdown.routes");
const flashSaleLiveStatsRoutes = require("./flashSaleLiveStats.routes");
const flashSaleRuleConfigRoutes = require("./flashSaleRuleConfig.routes");
const adminCategoriesRoutes = require("./adminCategories.routes");
const adminCargoRoutes = require("./adminCargo.routes");
const adminFooterRoutes = require("./adminFooter.routes");
const adminNavbarRoutes = require("./adminNavbar.routes");
const adminHomeBannersRoutes = require("./adminHomeBanners.routes");
const adminVideoBannersRoutes = require("./adminVideoBanners.routes");
const adminUzWarehouseRoutes = require("./adminUzWarehouse.routes");
const adminUzbProductDeliveryInfoRoutes = require("./adminUzbProductDeliveryInfo.routes");
const adminShippingCountryRoutes = require("./adminShippingCountry.routes");
const adminProductTypeRoutes = require("./adminProductType.routes");
const adminProductPolicyRoutes = require("./adminProductPolicy.routes");
const adminProductsRoutes = require("./adminProducts.routes");
const adminCustomerStatisticsRoutes = require("./adminCustomerStatistics.routes");
const adminSalesStatisticsRoutes = require("./adminSalesStatistics.routes");
const adminCustomerListRoutes = require("./adminCustomerList.routes");
const adminFlashCategoryRoutes = require("./adminFlashCategory.routes");
const activityRoutes = require("./activity.routes");
const adminUploadRoutes = require("./adminUpload.routes");
const sellerSubscriptionRoutes = require("./sellerSubscription.routes");
const commentRoutes = require("./comment.routes");
const pendingReviewRoutes = require("./pendingReview.routes");
const sellerAuthRoutes = require("./sellerAuth.routes");
const adminSellerApplicationsRoutes = require("./adminSellerApplications.routes");
const adminSellerManagementRoutes = require("./adminSellerManagement.routes");
const adminPaymentRequestRoutes = require("./adminPaymentRequest.routes");
const adminWithdrawalRoutes = require("./adminWithdrawal.routes");
const adminNotificationRoutes = require("./adminNotification.routes");
const messageChatRoutes = require("./messageChat.routes");
const chatsPageSearchRoutes = require("./chatsPageSearch.routes");
const userOrderTrackingRoutes = require("./userOrderTracking.routes");
const deliveryAuthRoutes = require("./deliveryAuth.routes");
const adminCourierRoutes = require("./adminCourier.routes");
const logisticaAuthRoutes = require("./logisticaAuth.routes");
const logisticaShipmentsRoutes = require("./logisticaShipments.routes");
const adminLogisticaRoutes = require("./adminLogistica.routes");
const adminCargoShipmentsRoutes = require("./adminCargoShipments.routes");
const adminOrdersRoutes = require("./adminOrders.routes");
const adminReturnRequestRoutes = require("./adminReturnRequest.routes");
const adminReturnedProductsRoutes = require("./adminReturnedProducts.routes");
const adminCustomerRefundRoutes = require("./adminCustomerRefund.routes");
const supportChatRoutes = require("./supportChat.routes");
const deliveryOrdersRoutes = require("./deliveryOrders.routes");

const router = express.Router();

router.use(productsRoutes);
router.use(categoriesRoutes);
router.use(navbarRoutes);
router.use(homeBannersRoutes);
router.use(footerRoutes);
router.use(cargoRoutes);
router.use(videoBannersRoutes);
router.use(collectionRoutes);
router.use(sellerRoutes);
router.use(sellersRoutes);
router.use(topSellersRoutes);
router.use(defaultProductPolicyRoutes);
router.use(uzWarehouseRoutes);
router.use(uzbProductDeliveryInfoRoutes);
router.use(loginRoutes);
router.use(profileRoutes);
router.use(wishlistRoutes);
router.use(cartRoutes);
router.use(searchRoutes);
router.use(viewedAtRoutes);
router.use(recommendationRoutes);
router.use(flashSaleLiveStatsRoutes);
router.use(flashSaleCountdownRoutes);
router.use(flashSaleRuleConfigRoutes);
router.use(adminCategoriesRoutes);
router.use(adminCargoRoutes);
router.use(adminFooterRoutes);
router.use(adminNavbarRoutes);
router.use(adminHomeBannersRoutes);
router.use(adminVideoBannersRoutes);
router.use(adminUzWarehouseRoutes);
router.use(adminUzbProductDeliveryInfoRoutes);
router.use(adminShippingCountryRoutes);
router.use(adminProductTypeRoutes);
router.use(adminProductPolicyRoutes);
router.use(adminProductsRoutes);
router.use(adminCustomerStatisticsRoutes);
router.use(adminSalesStatisticsRoutes);
router.use(adminCustomerListRoutes);
router.use(adminFlashCategoryRoutes);
router.use(activityRoutes);
router.use(adminUploadRoutes);
router.use(sellerSubscriptionRoutes);
router.use(commentRoutes);
router.use(pendingReviewRoutes);
router.use(sellerAuthRoutes);
router.use(adminSellerApplicationsRoutes);
router.use(adminSellerManagementRoutes);
router.use(adminPaymentRequestRoutes);
router.use(adminWithdrawalRoutes);
router.use(adminNotificationRoutes);
router.use(messageChatRoutes);
router.use(chatsPageSearchRoutes);
router.use(userOrderTrackingRoutes);
router.use(deliveryAuthRoutes);
router.use(adminCourierRoutes);
router.use(logisticaAuthRoutes);
router.use(logisticaShipmentsRoutes);
router.use(adminLogisticaRoutes);
router.use(adminCargoShipmentsRoutes);
router.use(adminOrdersRoutes);
router.use(adminReturnRequestRoutes);
router.use(adminReturnedProductsRoutes);
router.use(adminCustomerRefundRoutes);
router.use(supportChatRoutes);
router.use(deliveryOrdersRoutes);

module.exports = router;
